function [qp, ep, res, qv] = CylWaveguideMode(nv,rv,m)

% function determines the axial wave vector components for cylindrical waveguide modes
% (c) Joerg Enderlein (2005)

nv = nv(:).'; rv = rv(:).';
dq = 1e-4; % determines the finesse of searching; if waveguide modes are closer than this spacing one has a problem
qv = min(nv)+dq/2:dq:max(nv)-dq/2;

len = length(rv);

res = zeros(1,length(qv));
for jq=1:length(qv)
    q = qv(jq);
    wv = sqrt(nv.^2-q^2);
    wv(imag(wv)<0) = conj(wv(imag(wv)<0));
    if len==1
        r = rv; n2 = nv(2); n1 = nv(1); w2 = wv(2); w1 = wv(1);
        M = [CylM(m,w2,r,'h','f'), CylN(m,w2,n2,r,'h','f'), -CylM(m,w1,r,'j','f'), -CylN(m,w1,n1,r,'j','f'); ...
            0, CylN(m,w2,n2,r,'h','z'), 0, -CylN(m,w1,n1,r,'j','z'); ...
            CylN(m,w2,n2,r,'h','f'), n2^2*CylM(m,w2,r,'h','f'), -CylN(m,w1,n1,r,'j','f'), -n1^2*CylM(m,w1,r,'j','f'); ...
            CylN(m,w2,n2,r,'h','z'), 0, -CylN(m,w1,n1,r,'j','z'), 0; ...
            ];
        %res(jq) = (det([real(M) -imag(M); imag(M) real(M)]));
        res(jq) = real(det(M));
    else
        M = zeros(4*len, 4*len);
        r = rv(end); n2 = nv(end); n1 = nv(end-1); w2 = wv(end); w1 = wv(end-1);
        M(1:4,1:6) = [ ...
            CylM(m,w2,r,'h','f'), CylN(m,w2,n2,r,'h','f'), -CylM(m,w1,r,'j','f'), -CylN(m,w1,n1,r,'j','f'), -CylM(m,w1,r,'h','f'), -CylN(m,w1,n1,r,'h','f'); ...
            0, CylN(m,w2,n2,r,'h','z'), 0, -CylN(m,w1,n1,r,'j','z'), 0, -CylN(m,w1,n1,r,'h','z'); ...
            CylN(m,w2,n2,r,'h','f'), n2^2*CylM(m,w2,r,'h','f'), -CylN(m,w1,n1,r,'j','f'), -n1^2*CylM(m,w1,r,'j','f'), -CylN(m,w1,n1,r,'h','f'), -n1^2*CylM(m,w1,r,'h','f'); ...
            CylN(m,w2,n2,r,'h','z'), 0, -CylN(m,w1,n1,r,'j','z'), 0, -CylN(m,w1,n1,r,'h','z'), 0; ...
            ];
        cnt = 1;
        for k=length(nv)-1:-1:3
            r = rv(k-1); n2 = nv(k); n1 = nv(k-1); w2 = wv(k); w1 = wv(k-1);
            M(1+(4*cnt:4*(cnt+1)),-2+4*cnt+(1:8)) = [ ...
                CylM(m,w2,r,'j','f'), CylN(m,w2,n2,r,'j','f'), CylM(m,w2,r,'h','f'), CylN(m,w2,n2,r,'h','f'), -CylM(m,w1,r,'j','f'), -CylN(m,w1,n1,r,'j','f'), -CylM(m,w1,r,'h','f'), -CylN(m,w1,n1,r,'h','f'); ...
                0, CylN(m,w2,n2,r,'j','z'), 0, CylN(m,w2,n2,r,'h','z'), 0, -CylN(m,w1,n1,r,'j','z'), 0, -CylN(m,w1,n1,r,'h','z'); ...
                CylN(m,w2,n2,r,'j','f'), n2^2*CylM(m,w2,r,'j','f'), CylN(m,w2,n2,r,'h','f'), n2^2*CylM(m,w2,r,'h','f'), -CylN(m,w1,n1,r,'j','f'), -n1^2*CylM(m,w1,r,'j','f'), -CylN(m,w1,n1,r,'h','f'), -n1^2*CylM(m,w1,r,'h','f'); ...
                CylN(m,w2,n2,r,'j','z'), 0, CylN(m,w2,n2,r,'h','z'), 0, -CylN(m,w1,n1,r,'j','z'), 0, -CylN(m,w1,n1,r,'h','z'), 0; ...
                ];
            cnt = cnt +1;
        end
        r = rv(1); n2 = nv(2); n1 = nv(1); w2 = wv(2); w1 = wv(1);
        M(end-3:end,end-5:end) = [
            CylM(m,w2,r,'j','f'), CylN(m,w2,n2,r,'j','f'), CylM(m,w2,r,'h','f'), CylN(m,w2,n2,r,'h','f'), -CylM(m,w1,r,'j','f'), -CylN(m,w1,n1,r,'j','f'); ...
            0, CylN(m,w2,n2,r,'j','z'), 0, CylN(m,w2,n2,r,'h','z'), 0, -CylN(m,w1,n1,r,'j','z'); ...
            CylN(m,w2,n2,r,'j','f'), n2^2*CylM(m,w2,r,'j','f'), CylN(m,w2,n2,r,'h','f'), n2^2*CylM(m,w2,r,'h','f'), -CylN(m,w1,n1,r,'j','f'), -n1^2*CylM(m,w1,r,'j','f'); ...
            CylN(m,w2,n2,r,'j','z'), 0, CylN(m,w2,n2,r,'h','z'), 0, -CylN(m,w1,n1,r,'j','z'), 0; ...
            ];
        res(jq) = real(det(M));
    end
end

tv = 1:length(qv);
t = tv(res(1:end-1).*res(2:end)<0);
% t = tv(maxl(-res));
qp = zeros(1,length(t));
ep = zeros((length(nv)-1)*4,length(t));
for j=1:length(t)
    ind = max([1 t(j)-2]):min([length(qv) t(j)+3]);
    %qp(j) = interp1(res(ind).*((tv(ind)<=t(j))-0.5), qv(ind), 0);
    qp(j) = interp1(res(ind), qv(ind), 0, 'cubic');
    q = qp(j);
    wv = sqrt(nv.^2-q^2);
    wv(imag(wv)<0) = conj(wv(imag(wv)<0));
    if len==1
        r = rv; n2 = nv(2); n1 = nv(1); w2 = wv(2); w1 = wv(1);
        M = [CylM(m,w2,r,'h','f'), CylN(m,w2,n2,r,'h','f'), -CylM(m,w1,r,'j','f'), -CylN(m,w1,n1,r,'j','f'); ...
            0, CylN(m,w2,n2,r,'h','z'), 0, -CylN(m,w1,n1,r,'j','z'); ...
            CylN(m,w2,n2,r,'h','f'), n2^2*CylM(m,w2,r,'h','f'), -CylN(m,w1,n1,r,'j','f'), -n1^2*CylM(m,w1,r,'j','f'); ...
            CylN(m,w2,n2,r,'h','z'), 0, -CylN(m,w1,n1,r,'j','z'), 0; ...
            ];
    else
        M = zeros(4*len, 4*len);
        r = rv(end); n2 = nv(end); n1 = nv(end-1); w2 = wv(end); w1 = wv(end-1);
        M(1:4,1:6) = [ ...
            CylM(m,w2,r,'h','f'), CylN(m,w2,n2,r,'h','f'), -CylM(m,w1,r,'j','f'), -CylN(m,w1,n1,r,'j','f'), -CylM(m,w1,r,'h','f'), -CylN(m,w1,n1,r,'h','f'); ...
            0, CylN(m,w2,n2,r,'h','z'), 0, -CylN(m,w1,n1,r,'j','z'), 0, -CylN(m,w1,n1,r,'h','z'); ...
            CylN(m,w2,n2,r,'h','f'), n2^2*CylM(m,w2,r,'h','f'), -CylN(m,w1,n1,r,'j','f'), -n1^2*CylM(m,w1,r,'j','f'), -CylN(m,w1,n1,r,'h','f'), -n1^2*CylM(m,w1,r,'h','f'); ...
            CylN(m,w2,n2,r,'h','z'), 0, -CylN(m,w1,n1,r,'j','z'), 0, -CylN(m,w1,n1,r,'h','z'), 0; ...
            ];
        cnt = 1;
        for k=length(nv)-1:-1:3
            r = rv(k-1); n2 = nv(k); n1 = nv(k-1); w2 = wv(k); w1 = wv(k-1);
            M(1+(4*cnt:4*(cnt+1)),-2+4*cnt+(1:8)) = [ ...
                CylM(m,w2,r,'j','f'), CylN(m,w2,n2,r,'j','f'), CylM(m,w2,r,'h','f'), CylN(m,w2,n2,r,'h','f'), -CylM(m,w1,r,'j','f'), -CylN(m,w1,n1,r,'j','f'), -CylM(m,w1,r,'h','f'), -CylN(m,w1,n1,r,'h','f'); ...
                0, CylN(m,w2,n2,r,'j','z'), 0, CylN(m,w2,n2,r,'h','z'), 0, -CylN(m,w1,n1,r,'j','z'), 0, -CylN(m,w1,n1,r,'h','z'); ...
                CylN(m,w2,n2,r,'j','f'), n2^2*CylM(m,w2,r,'j','f'), CylN(m,w2,n2,r,'h','f'), n2^2*CylM(m,w2,r,'h','f'), -CylN(m,w1,n1,r,'j','f'), -n1^2*CylM(m,w1,r,'j','f'), -CylN(m,w1,n1,r,'h','f'), -n1^2*CylM(m,w1,r,'h','f'); ...
                CylN(m,w2,n2,r,'j','z'), 0, CylN(m,w2,n2,r,'h','z'), 0, -CylN(m,w1,n1,r,'j','z'), 0, -CylN(m,w1,n1,r,'h','z'), 0; ...
                ];
            cnt = cnt +1;
        end
        r = rv(1); n2 = nv(2); n1 = nv(1); w2 = wv(2); w1 = wv(1);
        M(end-3:end,end-5:end) = [
            CylM(m,w2,r,'j','f'), CylN(m,w2,n2,r,'j','f'), CylM(m,w2,r,'h','f'), CylN(m,w2,n2,r,'h','f'), -CylM(m,w1,r,'j','f'), -CylN(m,w1,n1,r,'j','f'); ...
            0, CylN(m,w2,n2,r,'j','z'), 0, CylN(m,w2,n2,r,'h','z'), 0, -CylN(m,w1,n1,r,'j','z'); ...
            CylN(m,w2,n2,r,'j','f'), n2^2*CylM(m,w2,r,'j','f'), CylN(m,w2,n2,r,'h','f'), n2^2*CylM(m,w2,r,'h','f'), -CylN(m,w1,n1,r,'j','f'), -n1^2*CylM(m,w1,r,'j','f'); ...
            CylN(m,w2,n2,r,'j','z'), 0, CylN(m,w2,n2,r,'h','z'), 0, -CylN(m,w1,n1,r,'j','z'), 0; ...
            ];
    end
    ep(:,j) = [1; -(M(:,2:end)\M(:,1))];
end


