function  str=rat2str(x)
%
%  Generated by David Y. Hsu.
%  Please acknowledge when using this program.
%  dhsu@littongcs.com
%
%  x is a real number
%  str is a string expressing x in rational form
%  example: x=pi
%           s=rat2str(x)
%           s='355/113'

[N,D]=rat(x);
str=[int2str(N),'/',int2str(D)];
